import type { Metadata } from "next";
import { Geist, Geist_Mono,Lexend } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const lexendBold = Lexend({
  weight: "700",
  variable: "--font-lexend",
  subsets: ["latin"],
});

const lexendSemiBold = Lexend({
  weight: "600",
  variable: "--font-lexend",
  subsets: ["latin"],
});

const lexendRegular = Lexend({
  weight: "400",
  variable: "--font-lexend",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "YY Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
